project_name: ABR Control
pkg_name: abr_control
repo_name: abr/abr_control
author_email: travis.dewolf@appliedbrainresearch.com
description: Robotic arm control in Python

copyright_start: 2017

license_rst: {
    type: nengo
}

contributing_rst: {}

# contributors_rst: {}

setup_py:
  url: https://github.com/abr/abr_control
  install_req:
    - cloudpickle>=0.8.0
    - cython>=0.29.0
    - matplotlib>=3.0.0
    - numpy>=1.16.0
    - setuptools>=18.0
    - scipy>=1.1.0
    - sympy>=1.3
  tests_req:
    - pytest>=4.4.0
    - pytest-xdist>=1.26.0
    - pytest-cov>=2.6.0
    - pytest-plt
    - coverage>=4.5.0
    - nengo>=2.8.0
  classifiers:
    - "Development Status :: 5 - Production/Stable"
    - "Framework :: ABR Control"
    - "Intended Audience :: Science/Research"
    - "License :: Free for non-commercial use"
    - "Operating System :: OS Independent"
    - "Programming Language :: Python :: 3 :: Only"
    - "Programming Language :: Python :: 3.6"
    - "Programming Language :: Python :: 3.7"
    - "Topic :: Scientific/Engineering :: Artificial Intelligence"

setup_cfg:
  codespell:
    ignore_words:
      - DOF
      - dof
      - hist
      - nd
      - compiletime
  coverage:
    omit_files:
      - "abr_control/_vendor/*"
      - "abr_control/interfaces/coppeliasim_files/*"
      - "abr_control/arms/threejoint/arm_files/*"
  flake8:
    exclude:
      - "abr_control/_vendor/*"
      - "abr_control/interfaces/coppeliasim_files/*"
      - "abr_control/arms/threejoint/arm_files/*"
      - "abr_control/utils/transformations.py"
    ignore:
      - C901
      - E402
      - E722
  pytest:
    norecursedirs:
      - examples
      - _vendor
  pylint:
    ignore:
      - _vendor
      - arm_files
      - coppeliasim_files
      - transformations.py
    disable:
      - F0001
      - C0116
      - C0115
      - C0114
      - too-many-blank-lines
      - W504
      - W0621
      - W0702
    known_third_party:
      - mpl_toolkits
      - nengo
      - nengolib
      - scipy

travis_yml:
  jobs:
    - script: static
    - script: test-coverage
      test_args: --plots
  pypi_user: tbekolay
  deploy_dists:
      - sdist
      - bdist_wheel

ci_scripts:
  - template: test
    output_name: test-coverage
    coverage: true

codecov_yml: {}

pre_commit_config_yaml: {}
pyproject_toml: {}
